### ISSUE TITLE
Sparknotation.init() with Gson and Kotlin

### ISSUE THREAD

**Issue by mbayou** [lamarios/sparknotation#2]
Hi,

I'm trying to use your project, I want to build a backend architecture with it for my personal project.

So right now I'm trying to use the Sparknotation.init() with Gson, I have some troubles at the compile time. I thing it's maybe due to the Kotlin compilation.

```
Cannot choose among the following candidates without completing type inference: 
public open fun <T : Any!> fromJson(p0: JsonElement!, p1: Class<(???..???)>!): (???..???) defined in com.google.gson.Gson
public open fun <T : Any!> fromJson(p0: JsonElement!, p1: Type!): (???..???) defined in com.google.gson.Gson
public open fun <T : Any!> fromJson(p0: JsonReader!, p1: Type!): (???..???) defined in com.google.gson.Gson
public open fun <T : Any!> fromJson(p0: Reader!, p1: Class<(???..???)>!): (???..???) defined in com.google.gson.Gson
public open fun <T : Any!> fromJson(p0: Reader!, p1: Type!): (???..???) defined in com.google.gson.Gson
public open fun <T : Any!> fromJson(p0: String!, p1: Class<(???..???)>!): (???..???) defined in com.google.gson.Gson
public open fun <T : Any!> fromJson(p0: String!, p1: Type!): (???..???) defined in com.google.gson.Gson
```
I understand the problem and I want to propose you something, maybe create some specific BodyTransformer like a GsonTransformer and add it to your library should be a good idea to avoid this kind of difficulties, what do you think ?

Btw thanks for this project, I'm really happy to see I'm not alone to prefer the annotation instead the express way to declare my resources.

**Comment by lamarios** [comment]
I don't really understand the issue.

For the GsonTransformer you will need to create one on your side. I'd like to avoid adding this to the library itself because user should be able to choose their own JSON library and not have an extra dependency that they might not use.



Here's a Java example of GsonTransformer
```java
public class GsonTransformer implements ResponseTransformer {
    public static final Gson GSON = new Gson();


    @Override
    public String render(Object o) throws Exception {
        return GSON.toJson(o);
    }
}
```

Glad you like the project :)

**Comment by mbayou** [comment]
Hi,

Sorry I made a mistake in my message, it was about the body transformer, this part : 

```
Gson gson = new Gson();
Sparknotation.init(gson::fromJson);
```

But after all you're right, I am agree about the fact all users can be free to use any transformer (for request body and response). It was just add some easier ways but still keep the general way.

I hope it's a little bit more clear.

**Comment by lamarios** [comment]
I see,  are you still facing the issue ? 
I'm using it successfully in this project:

https://github.com/lamarios/SpendSpentSpent/blob/master/src/main/java/com/ftpix/sss/SpendSpentSpent.java  (don't try to build it, it's a mess right now)

**Comment by mbayou** [comment]
Yes, but I made a little change, I create a class who extends the `BodyTransformer`. Like this : 

GsonBodyTransformer.kt
```kotlin
class GsonBodyTransformer : BodyTransformer {
    private val gson: Gson = Gson()

    override fun <T : Any?> transform(p0: String?, p1: Class<T>?): T {
        return gson.fromJson(p0, p1)
    }
}
```

```kotlin
Sparknotation.init(GsonBodyTransformer())
```

Now all works well but I can't use the simple way like describe in the documentation. Maybe this issue only appear with kotlin ? It's strange because for me it should be the same...

**Comment by lamarios** [comment]
Yes Probably an issue with Kotlin, I've been using this way of doing for Sparkjava alone and Sparknotation for a while now and never had an issue. You might want to try with plain Sparkjava see if you have the same issue, if you do check with kotlin users because i really can't help.
