### ISSUE TITLE
Maven repository url 

### ISSUE THREAD

**Issue by dparamoshkin** [lamarios/sparknotation#4]
it seems like URL doesn't work anymore, got "400: Invalid request" response

**Comment by lamarios** [comment]
Are you using version 1.9 ? It seems that using github as a repository will only keep the last version.

I'll put it on maven central when I have a bit of time.

**Comment by lamarios** [comment]
Ok, I've set up to use maven central instead. with a newer version, you can have a look at the README.
It usually takes a bit of time to propagate to maven central though.
